name: Tests
on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.yml'
      - '**.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '**.py'

jobs:
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:

    - uses: actions/checkout@v3
    
    - name: Test with pytest
      run: pytest tests/ --verbose --failed-first --cov=sarcgraph --cov-report=xml --disable-warnings
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        fail_ci_if_error: true
        files: ./coverage.xml # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        verbose: true